apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-front-wxmer
  namespace: shouft-dev
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ../charts/dev/frontservice
      sourceRef:
        kind: GitRepository
        name: shouft
        namespace: gitops-system
  interval: 1m0s
  targetNamespace: shouft-dev
  values:
    nameOverride: front-wxmer
    fullnameOverride: front-wxmer
    image:
      repository: harbor.zfmgr.top/zhongzf/shouft-front-wxmer
      tag: 1.0.0-alpha.20220429055705 # {"$imagepolicy": "shouft-dev:dev-front-wxmer:tag"}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
      - host: dev-shouft-wx.zfmgr.top
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: front-wxmer
            servicePort: 80
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: dev-front-wxmer
  namespace: shouft-dev
spec:
  image: harbor.zfmgr.top/zhongzf/shouft-front-wxmer
  interval: 1m0s
  secretRef:
    name: harborcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dev-front-wxmer
  namespace: shouft-dev
spec:
  imageRepositoryRef:
    name: dev-front-wxmer
  filterTags:
    pattern: '.*-alpha.*'
  policy:
    semver:
      range: '>0.x.x-alpha.x'
