apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: shouft-dev-service-autoupdate
  namespace: shouft-dev
spec:
  sourceRef:
    kind: GitRepository
    name: shouft
    namespace: gitops-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: gitopsbot
        email: public_tech@zfzfpay.cn
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  update:
    path: ./apps/dev
    strategy: Setters