apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-resource-service
  namespace: shouft-dev
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ../charts/dev/microservice
      sourceRef:
        kind: GitRepository
        name: shouft
        namespace: gitops-system
  interval: 1m0s
  targetNamespace: shouft-dev
  values:
    nameOverride: resource-service
    fullnameOverride: resource-service
    image:
      repository: harbor.zfmgr.top/zhongzf/shouft-service-resource
      tag: 1.0.0-alpha.20230412162950 # {"$imagepolicy": "shouft-dev:dev-resource-service:tag"}
    service:
      port: 80
      targetPort: 7008
      job:
        enabled: true
    startupProbe:
      httpGet:
        port: 7008
    livenessProbe:
      httpGet:
        port: 7008
    readinessProbe:
      httpGet:
        port: 7008
    env:
    - name: TZ
      value: Asia/Shanghai
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: JAVA_TOOL_OPTIONS
      value: -Xms768M -Xmx768M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dhttp.proxyHost=8.129.108.251 -Dhttp.proxyPort=8128 -Dhttps.proxyHost=8.129.108.251 -Dhttps.proxyPort=8128 -Dhttp.nonProxyHosts=\"localhost|127.0.0.1|172.*|10.*|192.*|*.cluster.local|*.zfmgr.top|*service\"
    # persistence:
    #   enabled: true
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: dev-resource-service
  namespace: shouft-dev
spec:
  image: harbor.zfmgr.top/zhongzf/shouft-service-resource
  interval: 1m0s
  secretRef:
    name: harborcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dev-resource-service
  namespace: shouft-dev
spec:
  imageRepositoryRef:
    name: dev-resource-service
  filterTags:
    pattern: '.*-alpha.*'
  policy:
    semver:
      range: '>0.x.x-alpha.x'
