apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-support-plug-service
  namespace: shouft-dev
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ../charts/dev/microservice
      sourceRef:
        kind: GitRepository
        name: shouft
        namespace: gitops-system
  interval: 1m0s
  targetNamespace: shouft-dev
  values:
    replicaCount: 1
    nameOverride: support-plug-service
    fullnameOverride: support-plug-service
    image:
      repository: harbor.zfmgr.top/zhongzf/shouft-plug-support
      tag: 1.0.0-alpha.20230306112152 # {"$imagepolicy": "shouft-dev:dev-support-plug-service:tag"}
    service:
      port: 80
      targetPort: 10000
    startupProbe:
      httpGet:
        port: 10000
    livenessProbe:
      httpGet:
        port: 10000
    readinessProbe:
      httpGet:
        port: 10000
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: dev-support-plug-service
  namespace: shouft-dev
spec:
  image: harbor.zfmgr.top/zhongzf/shouft-plug-support
  interval: 1m0s
  secretRef:
    name: harborcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dev-support-plug-service
  namespace: shouft-dev
spec:
  imageRepositoryRef:
    name: dev-support-plug-service
  filterTags:
    pattern: '.*-alpha.*'
  policy:
    semver:
      range: '>0.x.x-alpha.x'
